# Generated by Django 4.2.11 on 2024-04-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮件')),
                ('avatar', models.CharField(max_length=254, verbose_name='头像')),
                ('addresses', models.CharField(max_length=2000, verbose_name='地址')),
            ],
        ),
    ]
