# Generated by Django 4.2.11 on 2024-04-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='商品名称')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('quantity', models.IntegerField(default=0, verbose_name='库存数量')),
                ('spec_param', models.CharField(max_length=300, verbose_name='规格参数')),
                ('category', models.CharField(max_length=300, verbose_name='种类')),
                ('comment', models.CharField(max_length=500, verbose_name='用户评价')),
                ('detail', models.CharField(max_length=1000, verbose_name='详细描述')),
                ('pictures', models.CharField(max_length=500)),
            ],
        ),
    ]
