# Generated by Django 4.2.11 on 2024-04-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avatar',
            field=models.CharField(default='https://pic1.zhimg.com/v2-d52893c607cbd58ff48e2e08dcd72b2a_r.jpg', max_length=254, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(max_length=200, verbose_name='密码'),
        ),
    ]
