# Generated by Django 4.2.11 on 2024-04-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_useraccount_avatar_alter_useraccount_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(default='avatar/v2-d52893c607cbd58ff48e2e08dcd72b2a_r.jpg', null=True, upload_to='avatar', verbose_name='头像'),
        ),
    ]
