# Generated by Django 4.2.11 on 2024-04-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_useraccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='default_address',
            field=models.CharField(default='', max_length=200, verbose_name='默认地址'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='addresses',
            field=models.CharField(default='', max_length=2000, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='avatar',
            field=models.CharField(default='', max_length=254, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='邮件'),
        ),
    ]
