# Generated by Django 4.2.11 on 2024-04-12 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_useraccount_addresses_useraddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': '用户地址', 'verbose_name_plural': '用户地址'},
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.useraccount', verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=39, unique=True, verbose_name='会话密钥')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='account.useraccount')),
            ],
        ),
    ]
