# Generated by Django 4.2.11 on 2024-04-15 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('未支付', '未支付'), ('已支付', '已支付'), ('传输中', '传输中'), ('已完成', '传输中'), ('已取消', '已取消')], default='未支付', max_length=20, verbose_name='订单状态')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价格')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.useraccount', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='订单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '订单内容',
                'verbose_name_plural': '订单内容',
            },
        ),
    ]
