# Generated by Django 4.2.11 on 2024-04-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('未支付', '未支付'), ('已支付', '已支付'), ('传输中', '传输中'), ('已完成', '传输中'), ('已取消', '已取消')], default='未支付', max_length=20, verbose_name='订单状态'),
        ),
    ]
