# Generated by Django 4.2.11 on 2024-04-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='spec_param',
            field=models.CharField(max_length=3000, verbose_name='规格参数'),
        ),
    ]
