# Generated by Django 4.2.11 on 2024-04-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_spec_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.CharField(max_length=500, null=True, verbose_name='用户评价'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.CharField(max_length=1000, null=True, verbose_name='详细描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pictures',
            field=models.ImageField(null=True, upload_to='products', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, null=True, verbose_name='库存数量'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec_param',
            field=models.CharField(max_length=3000, null=True, verbose_name='规格参数'),
        ),
    ]
